project_id = "cuuefjpbgzulpaddczkk"

[db]
major_version = 15

[auth]
site_url = "https://lingua-bloom.ru"
additional_redirect_urls = [
  "https://lingua-bloom.ru/auth/callback",
  "http://localhost:3000/auth/callback",
  "http://localhost:3001/auth/callback",
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8
